spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dataspring
    username: root
    password: Root89
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        cache:
          use_second_level_cache: true
          region_prefix: org.hibernate.cache.jcache.internal.JCacheRegionFactory



logging:
  level:
    root: warn
  file:
    name:
      loggFile
    path: /


